name: Deploy Python API Astralis

on:
  push:
    branches:
      - develop    # Environnement DEV
      - master     # Environnement PROD
    paths:
      - 'Api_Python/**'
  workflow_dispatch:

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Zip artifact for deployment
        run: |
          cd Api_Python
          # On zip JUSTE le code et le requirements.txt
          # On exclut tout ce qui est lourd ou inutile
          zip -r ../python-app.zip . -x "venv/*" -x ".venv/*" -x "__pycache__/*" -x "*.git*" -x "*.pth" -x "*.pt" -x "*.pkl" -x "shared_models/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEV }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DEV }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DEV }}

      - name: Deploy to Azure Web App (DEV)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebAppAstralisApiPythonDev'
          package: ./python-app.zip
          startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 -w 4 -k uvicorn.workers.UvicornWorker app.main:app'

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Zip artifact for deployment
        run: |
          cd Api_Python
          # On zip JUSTE le code et le requirements.txt
          # On exclut tout ce qui est lourd ou inutile
          zip -r ../python-app.zip . -x "venv/*" -x ".venv/*" -x "__pycache__/*" -x "*.git*" -x "*.pth" -x "*.pt" -x "*.pkl" -x "shared_models/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BF887E68E9B422D8D5CDC815EA28D7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C901881CDC6644BB9B5969647791A4CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_380EDE8CE4834CE29176F66998D077C6 }}

      - name: Deploy to Azure Web App (PROD)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebAppAstralisApiPythonProd'
          package: ./python-app.zip
          startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 -w 4 -k uvicorn.workers.UvicornWorker app.main:app'
